[INFO] compiled with solc ver. 0.4.25
[INFO] all funcs : 61
[INFO] reachable : 25
[INFO] Generating Paths ... took 0.59829s
[INFO] # path : 6439

[INFO] Violate CEI: true
[INFO] msg.sender = this possible: false
[INFO] Performing Interval Analysis ... took 1.919431s
[STEP] Run analyzer
Sys_error("../fix_result/spank_chain_payment/reports/vulnerability_report.csv: No such file or directory")
Raised by primitive operation at Stdlib.open_in_gen in file "stdlib.ml", line 398, characters 28-54
Called from Stdlib.open_in in file "stdlib.ml" (inlined), line 403, characters 2-45
Called from Csv.Rows.load in file "src/csv.pp.ml", line 838, characters 30-43
Called from FixTarget.read_report in file "src/repair/fixTarget.ml", line 62, characters 13-73
Called from FixTarget.get_alarms in file "src/repair/fixTarget.ml", line 75, characters 12-34
Called from Repair.run in file "src/repair/repair.ml", line 389, characters 62-95
Called from Main.do_mode_job in file "src/main.ml", line 64, characters 18-45
Called from Main in file "src/main.ml", line 104, characters 12-19
